# Generated by Django 3.1.7 on 2021-02-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('street', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=512, verbose_name='Shop name')),
                ('house_name', models.CharField(max_length=64, verbose_name='House name')),
                ('opening_time', models.TimeField(verbose_name='Opening time')),
                ('closing_time', models.TimeField(verbose_name='Closing time')),
                ('city_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
                ('street_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street.street')),
            ],
        ),
    ]
