# Generated by Django 3.1.7 on 2021-02-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='city_pk',
        ),
    ]
